[project]
name = "schedule-fa-csv-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.2",
    "yfinance>=0.2.65",
    "openpyxl>=3.1.2",
]
